config/routes.rb
Rails.application.routes.draw do
  # get 'comments/create'
  resources :lections do
    post 'comments', to: "comments#create"
    #resources :comments, only: [:create, :destroy]
  end
  root to: 'pages#home'
  devise_for :users
  resources :users, only: [:update, :show, :destroy]
  get '/tagged', to: "lections#tagged", as: :tagged
  resources :tags
  post 'comments/like_dislike'
end

app/models/comment.rb
class Comment < ApplicationRecord
  acts_as_likeable
  has_many :likes
  belongs_to :user, optional: true
  belongs_to :lection, optional: true
  validates :body, presence: true, allow_blank: false

  after_create_commit {
    CommentBroadcastJob.perform_later(self)
  }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_lection, except: [:destroy, :like_dislike]
  before_action :authenticate_user!

  def create
    @comment = @lection.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
  end

  def like_dislike
    current_user.toggle_like!(Comment.find(params[:comment]))
    @comment_id = params[:comment]
    @likes_counter = Comment.find(params[:comment]).likers_count
    @user_liked = Comment.find(params[:comment]).liked_by?(current_user)
    respond_to do |format|
      format.js {
        render :template => 'comments/like_dislike.js.erb'
      }
    end
  end
  # def destroy
  #   @comment = @lection.comments.find(params[:id])
  #   @comment_id = @comment.id
  #   @comment.destroy
  # end

  private
  def comment_params
    params.require(:comment).permit (:body)
  end

  def set_lection
    @lection = Lection.find(params[:lection_id])
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="container">
  <div class="card my-4">
    <h5 class="card-header">
      <div id="comment-<%= comment.id %>">
      By  <strong><%= link_to comment.user.username, comment.user %> </strong>
      </h5>
      <div class="card-body">
      <%= comment.body %>
      <%#= link_to "Delete", lection_comment_path(@lection, comment),method: :delete, remote: true, style: 'float: right' %>
      <% if comment!=nil %>
     <div id="likes_counter<%= comment.id %>" class="btn btn-danger btn-sm float-right" > <%= comment.likers_count %>  </div>
     <% end %>
  <%= link_to "Like", { :controller => "comments", :action => "like_dislike", :comment => comment }, method: :post, remote: true, class: "btn btn-outline-danger btn-sm float-right", id: "like_button" + comment.id.to_s %>
      </div>
    <div class="card-footer text-muted">
        <%= time_ago_in_words(comment.created_at) %> ago
      </div>
    </div>
  </div>
</div>

app/views/comments/create.js.erb
// $('#comment_pane').prepend("<%= j render @comment %>");
$('#comment_body').val('');

app/views/comments/destroy.js.erb
// $('#comment-<%=@comment.id %>').html('');

app/views/comments/like_dislike.js.erb
document.getElementById("likes_counter<%= @comment_id %>").textContent = "<%= @likes_counter %>";
document.getElementById("like_button<%= @comment_id %>").textContent = "<%= @user_liked ? "Unlike" : "Like" %>";