config/routes.rb
Rails.application.routes.draw do
  # get 'comments/create'
  resources :lections do
    post 'comments', to: "comments#create"
    #resources :comments, only: [:create, :destroy]
  end
  root to: 'pages#home'
  devise_for :users
  resources :users, only: [:update, :show, :destroy]
  get '/tagged', to: "lections#tagged", as: :tagged
  resources :tags
  post 'comments/like_dislike'
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_liker
  has_many :comments, dependent: :destroy
  has_many :lections, dependent: :destroy
  before_create :confirmation_token
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :json
  def show
    @user = User.find(params[:id])
    @filterrific = initialize_filterrific(
      Lection,
      params[:filterrific],
      select_options: {
        :sorted_by => @user.lections.options_for_sorted_by
      },
      persistence_id: 'shared_key',
      default_filter_params: {},
      available_filters: [
        :sorted_by,
        :search_query,
        :with_speciality],
        sanitize_params: true
        ) or return
        @lections = @filterrific.find.page(params[:page])
        respond_to do |format|
          format.html
          format.js
        end

      rescue ActiveRecord::RecordNotFound => e
        # There is an issue with the persisted param_set. Reset it.
        puts "Had to reset filterrific params: #{ e.message }"
        redirect_to(reset_filterrific_url(format: :html)) and return
      end

      def update
        @user = User.find(params[:id])
        params.permit!
        @user.update_attributes(params[:user])
        respond_with @user
      end

    end

app/helpers/users_helper.rb
module UsersHelper
  def resource_name
    :user
end

def resource
    @resource ||= User.new
end

def resource_class
    User
end

def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
end
end

app/views/users/_change_email.html.erb
<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
<%= f.error_notification %>
<div class="form-inputs">

  <strong>  <label for="email"> Email address </label> </strong>
  <div><%= best_in_place @user, :email, required: true, id: "email", autofocus: true %> </div>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
  <p>Currently waiting confirmation for: <%= resource.unconfirmed_email %></p>
  <% end %>
  <strong><%= f.input :password, required: false, id: "new_password", input_html: { autocomplete: "new-password" } %>

  <%= f.input :password_confirmation,id: "confirm_password", required: false, input_html: { autocomplete: "new-password" } %>

  <%= f.input :current_password, required: true, id: "old_password", input_html: { autocomplete: "current-password" } %>
</strong>
</div>

<div class="form-actions">
  <%= f.button :submit, "Update",class: "btn btn-outline-info" %>
</div>
<% end %>

app/views/users/_edit_widget.html.erb
<div class="container">
  <div class="card">
    <div class="card-header">
      <h5> Profile editting </h5>
    </div>
    <div class="card-body">
    <strong>  <label for="username"> Username </label> </strong>
    <div><%= best_in_place @user, :username, :as => :input, id: "username"%></div>
    <%= render 'users/change_email' %>
    </div>
    <div class="card-footer text-muted">
    </div>
  </div>
</div>

app/views/users/_info_widget.html.erb
<div class="container">
  <div class="card">
    <div class="card-header">
      <h5> Information </h5>
    </div>
    <div class="card-body">
        <div>
        <%= @user.created_at.to_s.split('UTC')[0] %>
        </div>
        <%#=  @user.current_sign_in_at %>
        <strong> <%= @user.username %></strong>  has  <%= pluralize(@user.lections.count, "lection") %>
    </div>
  </div>
</div>

app/views/users/_lections_list.html.erb
<div id="filterrific_results">
  <table class="table table-striped table-bordered table-list">
    <tr>
      <th><%= filterrific_sorting_link(@filterrific, :title) %></th>
      <th><%= filterrific_sorting_link(@filterrific, :speciality) %></th>
      <th><%= filterrific_sorting_link(@filterrific, :description) %></th>
      <th><%= filterrific_sorting_link(@filterrific, :created_at) %></th>
      <th>Tags</th>
      <th>Actions</th>
    </tr>
    <% @user.lections.each do |lection| %>
    <tr>
      <td><%= lection.title %></td>
      <td><%= lection.speciality %></td>
      <td><%= truncate(lection.description, length: 20) %> </td>
      <td><%= lection.created_at.to_s.split('UTC')[0] %> </td>
      <td><% lection.tag_list.each do |tag| %>
        <span class="badge badge-pill badge-success"><%= tag %></span>
        <% end %>
      </td>
      <td><%= link_to "Show", lection_path(lection), class: "btn btn-outline-success" %>
        <% if current_user && current_user.admin || current_user == lection.user %>
        <%= link_to 'Edit', edit_lection_path(lection), class: "btn btn-outline-warning" %>
        <%= link_to 'Delete', lection_path(lection), method: :delete, class: "btn btn-outline-danger",
        data: { confirm: 'Are you sure?' } %>
        <% end %></td>
      </tr>
      <% end %>
    </table>
  </div>
  <%= will_paginate @lections %>

app/views/users/_user_profile.html.erb

  <div class="row">
    <div class="col-md-9">
      <div class="card">
        <div class = "card-header">
          <%= form_for_filterrific @filterrific do |f| %>
          <div class="row">
            <div class="col-md-4">
              Search
              <%= f.text_field :search_query,class: "filterrific-periodically-observed form-control", placeholder:"Search by title" %>
            </div>
            <div class="col-md-4">
              Speciality
              <%= f.text_field :with_speciality,class: "filterrific-periodically-observed form-control", placeholder:"filter by speciality" %>
            </div>
            <div class="float-right">
              <%= link_to('Reset filters',reset_filterrific_url, class: "btn btn-outline-info float-right btn-sm") %>
              <%= link_to 'New lection', new_lection_path , class: "btn btn-outline-info  float-right btn-sm" %>
            </div>
          </div>
          <% end %>
        </div>
        <div class = "card-body">
          <%= render( partial: 'users/lections_list', locals: { lection: @lections }) %>
          </div>
        </div>
      </div>
    <div class="col-md-3">
      <%= render 'users/edit_widget' if current_user %>
      <%= render 'users/info_widget' %>
    </div>
  </div>

app/views/users/show.html.erb
<%= render 'users/user_profile' %>

app/views/users/show.js.erb
<% js = escape_javascript(
  render(partial: 'users/lections_list', locals: { lections: @lections })
) %>
$("#filterrific_results").html("<%= js %>");