config/routes.rb
Rails.application.routes.draw do
  # get 'comments/create'
  resources :lections do
    post 'comments', to: "comments#create"
    #resources :comments, only: [:create, :destroy]
  end
  root to: 'pages#home'
  devise_for :users
  resources :users, only: [:update, :show, :destroy]
  get '/tagged', to: "lections#tagged", as: :tagged
  resources :tags
  post 'comments/like_dislike'
end

app/models/lection.rb
class Lection < ApplicationRecord
  has_many :comments, dependent: :destroy
  acts_as_taggable_on :tags
  belongs_to :user, optional: true
  validates :title, uniqueness: { scope: :user_id, message: "must be unique for each of your posts" }
  validates :body,presence: true,length: {maximum: 1500},on: :create,allow_nil: false

  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [
      :sorted_by,
      :search_query,
      :with_speciality
    ]
  )
  scope :with_speciality, lambda { |speciality|
     where(speciality: [*speciality])
  }
  scope :search_query, lambda { |query|
    # Searches the students table on the 'first_name' and 'last_name' columns.
    # Matches using LIKE, automatically appends '%' to each term.
    # LIKE is case INsensitive with MySQL, however it is case
    # sensitive with PostGreSQL. To make it work in both worlds,
    # we downcase everything.
    return nil  if query.blank?

    # condition query, parse into individual keywords
    terms = query.to_s.downcase.split(/\s+/)

    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conds = 1
    where(
      terms.map { |term|
        "(LOWER(lections.title) LIKE ?)"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conds }.flatten
    )
  }

  scope :sorted_by, lambda { |sort_option|
direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
case sort_option.to_s
when /^created_at_/
order("lecture_notes.created_at #{ direction }")
when /^title_/
order("LOWER(lecture_notes.title) #{ direction }")
when /^speciality/
order("LOWER(lecture_notes.speciality) #{ direction }")
when /^description/
order("LOWER(lecture_notes.description) #{ direction }")
else
raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
end
}
def self.options_for_sorted_by
    [
      ['Creation date (newest first)', 'created_at_desc'],
      ['Title (a-z)', 'title_asc'],
      ['Speciality (0-9)', 'speciality_asc']
    ]
  end
end

app/controllers/lections_controller.rb
class LectionsController < ApplicationController
  before_action :set_lection, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index,]
  # GET /lections
  # GET /lections.json
  def index
    @lections = Lection.all
      end

      def tag_cloud
        @tags = Lection.tag_counts_on(:tags)
      end
      def tagged
        if params[:tag].present?
          @lections = Lection.tagged_with(params[:tag])
        else
          @lections = Lection.all
        end
      end

      # GET /lections/1
      # GET /lections/1.json
      def show
        @comment = Comment.new
        @comments = @lection.comments.order( "updated_at DESC")
      end

      # GET /lections/new
      def new
        @lection = current_user.lections.new
      end

      # GET /lections/1/edit
      def edit
      end

      # POST /lections
      # POST /lections.json
      def create
        @lection = Lection.new(lection_params)
        @lection = current_user.lections.new(lection_params)
        respond_to do |format|
          if @lection.save
            format.html { redirect_to @lection, notice: 'Lection was successfully created.' }
            format.json { render :show, status: :created, location: @lection }
          else
            format.html { render :new }
            format.json { render json: @lection.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /lections/1
      # PATCH/PUT /lections/1.json
      def update
        respond_to do |format|
          if @lection.update(lection_params)
            format.html { redirect_to @lection, notice: 'Lection was successfully updated.' }
            format.json { render :show, status: :ok, location: @lection }
          else
            format.html { render :edit }
            format.json { render json: @lection.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /lections/1
      # DELETE /lections/1.json
      def destroy
        @lection.destroy
        respond_to do |format|
          format.html { redirect_to lections_url, notice: 'Lection was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private
      # Use callbacks to share common setup or constraints between actions.
      def set_lection
        @lection = Lection.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def lection_params
        params.require(:lection).permit(:title, :description, :speciality, :body, :tag_list)
      end

    rescue ActiveRecord::RecordNotFound => e
      # There is an issue with the persisted param_set. Reset it.
      puts "Had to reset filterrific params: #{ e.message }"
      redirect_to(reset_filterrific_url(format: :html)) and return
    end

app/helpers/lections_helper.rb
module LectionsHelper
     include ActsAsTaggableOn::TagsHelper
end
class Time
  def toDateTime
    dateTimeString = self.to_s.split
    localTimeString = "#{dateTimeString[1].split(':')[0].to_i + 3}:#{dateTimeString[1].split(':')[1]}:#{dateTimeString[1].split(':')[2]}"
    "#{dateTimeString[0].split('-').reverse.join('.')} #{localTimeString}"
  end
end

app/views/lections/_form.html.erb
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
  $(function() {
    var dataset_string = document.getElementById('tags').dataset.autocomplete;
    var available_tags = dataset_string.slice(2, dataset_string.length - 2).split('","')

    function split(val) {
      return val.split(/ \s*/);
    }

    function extractLast(term) {
      return split(term).pop();
    }

    $("#tags")
    .autocomplete({
      minLength: 0,
      source: function( request, response ) {
        response( $.ui.autocomplete.filter(
        available_tags, extractLast(request.term)));
      },
      focus: function() {
        return false;
      },
      select: function(event, ui) {
        var terms = split(this.value);
        terms.pop();

        terms.push( ui.item.value );
        terms.push( "" );
        this.value = terms.join( " " );
        return false;
      }
    });
  });
</script>
<%= form_with(model: lection, local: true) do |form| %>
<br>
<div class="container">

  <% if lection.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(lection.errors.count, "error") %> prohibited this lection from being saved:</h2>
    <ul>
      <% lection.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="card">
    <div class="card-body">

      <div class="row">
        <div class="col-md-12">
          <h5 class="card-header">Create new Lection</h5>
          <hr>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="form-group row">
          <div class= "col-4 col-form-label">
          <p>  Title </p>
          </div>
            <div class="col-8">
              <%= form.text_field :title, class: "form-control" %>
            </div>
          </div>

          <div class="form-group row">
            <div class= "col-4 col-form-label">
            <p>  Description </p>
            </div>
            <div class="col-8">
              <%= form.text_field :description, class: "form-control" %>
            </div>
          </div>

          <div class="form-group row">
            <div class= "col-4 col-form-label">
            <p>  Speciality </p>
            </div>
            <div class="col-8">
              <%= form.number_field :speciality, class: "form-control" %>
            </div>
          </div>

          <div class="form-group row">
            <div class= "col-4 col-form-label">
            <p> Body with <a href='https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet'> Markdown </a></p>
            </div>
            <div class="col-8">
              <%= form.text_area :body, class: "form-control", rows: 5 %>
            </div>
          </div>

          <div class="form-group row">
            <div class= "col-4 col-form-label">
            <p> Tags </p>
            </div>
            <div class="col-8">
              <%= form.text_field :tag_list, class: "form-control", id: "tags", data: {autocomplete: ActsAsTaggableOn::Tag.pluck(:name)} %>
            </div>
          </div>
          <div class="form-group row">
            <div class="offset-4 col-8">

            </div>
          </div>

        </div>
      </div>

      <div class="row">
        <hr>
        <div class="col-10">
          <%= link_to 'Back', lections_path, :class => "btn btn-primary" %>
        </div>

        <div class="col-2">
          <%= form.submit 'Create',:class => "btn btn-primary" %>
        </div>
      </div>

    </div>
  </div>
</div>
  <% end %>

app/views/lections/_lection.html.erb
<div class="card mb-4">
  <h6 class="card-header">
    <span data-toggle="tooltip" data-placement="left" title="Click here to see the profile">
  By <%=link_to lection.user.username, lection.user %>
            <div class="badge badge-pill badge-secondary float-right">Created at <%= lection.created_at.to_s.split('UTC')[0] %></div>
    </span>
  </h6>
  <div class="card-body">
    <span data-toggle="tooltip" data-placement="right" title="Click here to edit">
    <% if current_user%>
     <% if  current_user==lection.user  || current_user.admin %>
    <div class="btn-group dropright float-right">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"></a>
      <div class="dropdown-menu">
        <%= link_to 'Destroy', lection,class:"dropdown-item align-middle" , method: :delete, data: { confirm: 'Are you sure?' } %>
        <td><%= link_to 'Edit', edit_lection_path(lection),class:"dropdown-item align-middle" %></td>
        <a class="dropdown-item" href="#">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Separated link</a>
      </div>
    </div>
    <% end %>
    <% end %>
    <h1><%= lection.title %></h1>
    <hr>
    <h6 class="card-title"><%= lection.description %> | Speciality: <%= lection.speciality %> </h6>
    <hr>
    <% if lection.body.length > 250 %>
    <%= truncate(lection.body, length: 250) %>
    <% else %>
    <%= markdown(lection.body) %>
    <% end %>

  </div>
  <div class="card-footer text-muted">
    <% lection.tag_list.each do |tag| %>
    <span class="badge badge-pill badge-info"><%= tag %></span>
    <% end %>
    <%= link_to "Read More", lection ,class: "btn btn-outline-info float-right"%>
  </div>
</div>

app/views/lections/edit.html.erb
<h1>Editing Lection</h1>

<%= render 'form', lection: @lection %>

<%= link_to 'Show', @lection %> |
<%= link_to 'Back', lections_path %>

app/views/lections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lections</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Speciality</th>
      <th>Body</th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lections.each do |lection| %>
      <tr>
        <td><%= lection.title %></td>
        <td><%= lection.description %></td>
        <td><%= lection.speciality %></td>
        <td><%= markdown(lection.body) %></td>
        <td><%= lection.tag_list%></td>
        <td><%= link_to 'Show', lection %></td>
        <td><%= link_to 'Edit', edit_lection_path(lection) %></td>
        <td><%= link_to 'Destroy', lection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<td> <%= pluralize(lection.comments.count, "Comment") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lection', new_lection_path %>

app/views/lections/new.html.erb
<%= render 'form', lection: @lection %>

app/views/lections/show.html.erb
<div class="container">
  <div class="card mb-4">
    <h6 class="card-header">
      <span data-toggle="tooltip" data-placement="left" title="Click here to see the profile">
        By <%=link_to @lection.user.username, @lection.user  %>
        <div class="badge badge-pill badge-secondary float-right">Created at <%= @lection.created_at.toDateTime %></div>
      </span>
    </h6>
    <div class="card-body">
      <span data-toggle="tooltip" data-placement="right" title="Click here to edit">
        <% if current_user %>
        <% if  current_user==@lection.user  || current_user.admin %>
        <div class="btn-group dropleft float-right">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"></a>
          <div class="dropdown-menu">
            <%= link_to 'Destroy', @lection,class:"dropdown-item align-middle" , method: :delete, data: { confirm: 'Are you sure?' } %>
            <td><%= link_to 'Edit', edit_lection_path(@lection),class:"dropdown-item align-middle" %></td>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </div>
        <% end %>
        <% end %>
        <h1><%= @lection.title %></h1>
        <hr>
        <h6 class="card-title"><%= @lection.description %> | Speciality: <%= @lection.speciality %> </h6>
        <hr>
        <%= markdown(@lection.body) %>
      </div>
      <div class="card-footer text-muted">
        <% @lection.tag_list.each do |tag| %>
        <span class="badge badge-pill badge-info"><%= tag %></span>
        <% end %>
        <div class="badge badge-pill badge-primary float-right"> Updated at <%= @lection.updated_at.toDateTime %></div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="card">
      <div class="card-header">
        <h2>  Let's comment! </h2>
      </div>
      <div class="card-body">
        <% if current_user %>
        <%= form_with model: [@lection,@comment] do |f| %>
        <div class="row">
          <div class="col-md-10">
          <%= f.text_field :body, class: "form-control form-control-lg" %>
          </div>
          <%= f.submit "Comment", class:  "btn btn-outline-info" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <% else %>
  <p>
    You need to <%= link_to "Sign in", new_session_path %>
  </p>
  <% end %>
  <div id="comment_pane">
    <% @comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment %>
    <% end %>
  </div>
  <%= link_to 'Edit', edit_lection_path(@lection) %> |
  <%= link_to 'Back', lections_path %>